print("Here's the Menu")
print(" Coca Cola                    $0.27  ")
print(" Sprite                       $0.11  ")
print(" Pepsi                        $0.20  ")
print(" Red Bull                     $0.80  ")
print(" Monster                      $0.70  ")
print(" V                            $0.60  ")
print(" M&Ms                         $2.78  ")
print(" Cadbury                      $1.83  ")
print(" Skittles                     $2.71  ")
print(" Snickers                     $1.80  ")
print(" Mars                         $3.83  ")
print(" Kit Kat                      $3.38  ")
print()